### ISSUE TITLE
Fact in Uncategorized but renders correctly as well

### ISSUE THREAD

**Issue by michaelchadfleming** [Arelle/EDGAR#8]
We have a fact using us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations  in the cash flow statement that is included both in the CFS rendering and in "Uncategorized" rendering. We get the following warnings/errors:

[info] Columns in cash flow "Condensed Consolidated Statements of Cash Flows (Unaudited)" have maximum duration 9 months and at least 31 values. Shorter duration columns must have at least one fourth (7) as many values. Column "[2024-07-01 3m 2024-09-30]" is shorter (3 months) and has only 6 values, so it is being removed. - ctgo-20240930.htm 

[EXG.7.3.UncategorizedFact] us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations in context C_8f95ec2c-bea9-42ec-ba52-664001bca062 was not selected in any presentation group. Ensure there is a default member for axes in presentation roles {'http://www.contangoore.com/20240930/taxonomy/role/statement-condensed-consolidated-statements-of-cash-flows-unaudited'} - ctgo-20240930.htm 1704

The first warning indicates that the column has less than 7 values. That is correct; it only has six values for the CFS column and should should be suppressed. The second warning indicates that the fact is uncategorized but it should not exist in the suppressed column mentioned in the first warning.

However, the column that has less than 7 values and should be suppressed has 78 facts in report.embedding.factAxisMemberGroupList includes 78 facts.

https://github.com/Arelle/EDGAR/blob/80971bb135033963b9de3276e5fb18c0f3cacfa5/render/Filing.py#L1082

**Comment by austinmatherne-wk** [comment]
Hi Chad,

As far as I'm aware, the SEC team that builds the EDGAR plugins doesn't monitor issues posted here. They do have a support email address that you can contact though: StructuredData@sec.gov

**Comment by michaelchadfleming** [comment]
Thank you @austinmatherne-wk . I hope all is well! :)
